# Use Node.js
FROM node:18

# Set working directory
WORKDIR /app

# Install netcat so wait-for.sh can run
RUN apt-get update && apt-get install -y netcat-openbsd


# Copy package.json & install deps
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .
RUN chmod +x wait-for.sh

# Expose port
EXPOSE 5000

# Run server
CMD ["./wait-for.sh", "npm", "run", "dev"]
